// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Orion.Infrastructure.Persistence;

#nullable disable

namespace Orion.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(OrionDbContext))]
    [Migration("20261008004506_Salao")]
    partial class Salao
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("orion")
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Orion.Infrastructure.Persistence.Entities.Ambiente", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("integer")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("nome");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer")
                        .HasColumnName("ordem");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "Nome")
                        .IsUnique();

                    b.HasIndex("EmpresaId", "Ordem");

                    b.ToTable("ambientes", "orion");
                });

            modelBuilder.Entity("Orion.Infrastructure.Persistence.Entities.Atendimento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("AbertoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("aberto_em");

                    b.Property<string>("AbertoPorNome")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("aberto_por_nome");

                    b.Property<int>("AbertoPorUsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("aberto_por_usuario_id");

                    b.Property<long?>("AnfitriaoLugarId")
                        .HasColumnType("bigint")
                        .HasColumnName("anfitriao_lugar_id");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("integer")
                        .HasColumnName("empresa_id");

                    b.Property<DateTime?>("FechadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fechado_em");

                    b.Property<long>("MesaId")
                        .HasColumnType("bigint")
                        .HasColumnName("mesa_id");

                    b.Property<string>("ModoFechamento")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("modo_fechamento");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("MesaId");

                    b.HasIndex("EmpresaId", "Status");

                    b.ToTable("atendimentos", "orion");
                });

            modelBuilder.Entity("Orion.Infrastructure.Persistence.Entities.AtendimentoLugar", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AtendimentoId")
                        .HasColumnType("bigint")
                        .HasColumnName("atendimento_id");

                    b.Property<bool>("ContaFechada")
                        .HasColumnType("boolean")
                        .HasColumnName("conta_fechada");

                    b.Property<string>("NomeCliente")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nome_cliente");

                    b.Property<bool>("Ocupado")
                        .HasColumnType("boolean")
                        .HasColumnName("ocupado");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer")
                        .HasColumnName("ordem");

                    b.HasKey("Id");

                    b.HasIndex("AtendimentoId", "Ordem")
                        .IsUnique();

                    b.ToTable("atendimento_lugares", "orion");
                });

            modelBuilder.Entity("Orion.Infrastructure.Persistence.Entities.CartaCategoria", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("integer")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("nome");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer")
                        .HasColumnName("ordem");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "Nome")
                        .IsUnique();

                    b.ToTable("carta_categorias", "orion");
                });

            modelBuilder.Entity("Orion.Infrastructure.Persistence.Entities.CartaItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<long>("CategoriaId")
                        .HasColumnType("bigint")
                        .HasColumnName("categoria_id");

                    b.Property<string>("Destino")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("destino");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("integer")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("nome");

                    b.Property<decimal>("Preco")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("preco");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("EmpresaId", "CategoriaId");

                    b.ToTable("carta_itens", "orion");
                });

            modelBuilder.Entity("Orion.Infrastructure.Persistence.Entities.ComandaItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AtendimentoId")
                        .HasColumnType("bigint")
                        .HasColumnName("atendimento_id");

                    b.Property<DateTime?>("CanceladoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelado_em");

                    b.Property<string>("CanceladoPorNome")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("cancelado_por_nome");

                    b.Property<int?>("CanceladoPorUsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("cancelado_por_usuario_id");

                    b.Property<long?>("CartaItemId")
                        .HasColumnType("bigint")
                        .HasColumnName("carta_item_id");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("descricao");

                    b.Property<string>("Destino")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("destino");

                    b.Property<DateTime>("LancadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lancado_em");

                    b.Property<string>("LancadoPorNome")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("lancado_por_nome");

                    b.Property<int>("LancadoPorUsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("lancado_por_usuario_id");

                    b.Property<long?>("LugarId")
                        .HasColumnType("bigint")
                        .HasColumnName("lugar_id");

                    b.Property<string>("MotivoCancelamento")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("motivo_cancelamento");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("observacao");

                    b.Property<decimal>("PrecoUnitario")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("preco_unitario");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("AtendimentoId");

                    b.HasIndex("LugarId");

                    b.ToTable("comanda_itens", "orion");
                });

            modelBuilder.Entity("Orion.Infrastructure.Persistence.Entities.EntradaEstoque", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CanceladoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelado_em");

                    b.Property<int?>("CanceladoPorUsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("cancelado_por_usuario_id");

                    b.Property<string>("ChaveAcesso")
                        .HasMaxLength(44)
                        .HasColumnType("character varying(44)")
                        .HasColumnName("chave_acesso");

                    b.Property<Guid>("ChaveIdempotencia")
                        .HasColumnType("uuid")
                        .HasColumnName("chave_idempotencia");

                    b.Property<DateTime?>("ConfirmadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmado_em");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<int>("CriadoPorUsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("criado_por_usuario_id");

                    b.Property<DateTime?>("DataEmissao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_emissao");

                    b.Property<DateTime>("DataEntrada")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_entrada");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("integer")
                        .HasColumnName("empresa_id");

                    b.Property<string>("FornecedorCnpj")
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("fornecedor_cnpj");

                    b.Property<long?>("FornecedorId")
                        .HasColumnType("bigint")
                        .HasColumnName("fornecedor_id");

                    b.Property<string>("FornecedorNome")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("fornecedor_nome");

                    b.Property<string>("ModeloFiscal")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("modelo_fiscal");

                    b.Property<string>("NumeroNf")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("numero_nf");

                    b.Property<string>("Observacao")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("observacao");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("origem");

                    b.Property<string>("OrigemCadastro")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("origem_cadastro");

                    b.Property<string>("ReferenciaExternaCore")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("referencia_externa_core");

                    b.Property<string>("Serie")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("serie");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo");

                    b.Property<int>("UnidadeId")
                        .HasColumnType("integer")
                        .HasColumnName("unidade_id");

                    b.Property<decimal?>("ValorTotal")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("valor_total");

                    b.Property<string>("XmlOriginal")
                        .HasColumnType("text")
                        .HasColumnName("xml_original");

                    b.HasKey("Id");

                    b.HasIndex("ChaveIdempotencia")
                        .IsUnique();

                    b.HasIndex("EmpresaId", "ChaveAcesso")
                        .IsUnique()
                        .HasFilter("chave_acesso IS NOT NULL");

                    b.HasIndex("EmpresaId", "Status", "DataEntrada");

                    b.ToTable("entradas_estoque", "orion");
                });

            modelBuilder.Entity("Orion.Infrastructure.Persistence.Entities.EntradaEstoqueItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CodigoBarrasNf")
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("codigo_barras_nf");

                    b.Property<string>("DescricaoNf")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("descricao_nf");

                    b.Property<long>("EntradaEstoqueId")
                        .HasColumnType("bigint")
                        .HasColumnName("entrada_estoque_id");

                    b.Property<decimal>("FatorConversao")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(15, 4)
                        .HasColumnType("numeric(15,4)")
                        .HasDefaultValue(1m)
                        .HasColumnName("fator_conversao");

                    b.Property<string>("MotivoDivergencia")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("motivo_divergencia");

                    b.Property<long?>("MovimentacaoCoreId")
                        .HasColumnType("bigint")
                        .HasColumnName("movimentacao_core_id");

                    b.Property<string>("Ncm")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("ncm");

                    b.Property<string>("ProdutoCodigo")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("produto_codigo");

                    b.Property<int?>("ProdutoCoreId")
                        .HasColumnType("integer")
                        .HasColumnName("produto_core_id");

                    b.Property<decimal?>("QuantidadeNf")
                        .HasPrecision(15, 3)
                        .HasColumnType("numeric(15,3)")
                        .HasColumnName("quantidade_nf");

                    b.Property<decimal>("QuantidadeRecebida")
                        .HasPrecision(15, 3)
                        .HasColumnType("numeric(15,3)")
                        .HasColumnName("quantidade_recebida");

                    b.Property<string>("ReferenciaExternaItem")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("referencia_externa_item");

                    b.Property<string>("StatusVinculo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status_vinculo");

                    b.Property<string>("UnidadeComercialNf")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("unidade_comercial_nf");

                    b.Property<decimal?>("ValorUnitarioNf")
                        .HasPrecision(15, 4)
                        .HasColumnType("numeric(15,4)")
                        .HasColumnName("valor_unitario_nf");

                    b.HasKey("Id");

                    b.HasIndex("EntradaEstoqueId");

                    b.ToTable("entradas_estoque_itens", "orion");
                });

            modelBuilder.Entity("Orion.Infrastructure.Persistence.Entities.Fornecedor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("Cnpj")
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("cnpj");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("integer")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "Cnpj")
                        .IsUnique()
                        .HasFilter("cnpj IS NOT NULL");

                    b.HasIndex("EmpresaId", "Nome");

                    b.ToTable("fornecedores", "orion");
                });

            modelBuilder.Entity("Orion.Infrastructure.Persistence.Entities.MapaCodigoBarras", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("CodigoBarras")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("codigo_barras");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("integer")
                        .HasColumnName("empresa_id");

                    b.Property<int>("ProdutoCoreId")
                        .HasColumnType("integer")
                        .HasColumnName("produto_core_id");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "CodigoBarras")
                        .IsUnique();

                    b.ToTable("mapa_codigo_barras", "orion");
                });

            modelBuilder.Entity("Orion.Infrastructure.Persistence.Entities.Mesa", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AmbienteId")
                        .HasColumnType("bigint")
                        .HasColumnName("ambiente_id");

                    b.Property<long?>("AtendimentoAbertoId")
                        .HasColumnType("bigint")
                        .HasColumnName("atendimento_aberto_id");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("integer")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Forma")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("forma");

                    b.Property<int>("LugaresPadrao")
                        .HasColumnType("integer")
                        .HasColumnName("lugares_padrao");

                    b.Property<string>("Rotulo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("rotulo");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("situacao");

                    b.HasKey("Id");

                    b.HasIndex("AmbienteId");

                    b.HasIndex("AtendimentoAbertoId");

                    b.HasIndex("EmpresaId", "Rotulo")
                        .IsUnique();

                    b.ToTable("mesas", "orion");
                });

            modelBuilder.Entity("Orion.Infrastructure.Persistence.Entities.Atendimento", b =>
                {
                    b.HasOne("Orion.Infrastructure.Persistence.Entities.Mesa", "Mesa")
                        .WithMany()
                        .HasForeignKey("MesaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Mesa");
                });

            modelBuilder.Entity("Orion.Infrastructure.Persistence.Entities.AtendimentoLugar", b =>
                {
                    b.HasOne("Orion.Infrastructure.Persistence.Entities.Atendimento", "Atendimento")
                        .WithMany("Lugares")
                        .HasForeignKey("AtendimentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atendimento");
                });

            modelBuilder.Entity("Orion.Infrastructure.Persistence.Entities.CartaItem", b =>
                {
                    b.HasOne("Orion.Infrastructure.Persistence.Entities.CartaCategoria", "Categoria")
                        .WithMany("Itens")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("Orion.Infrastructure.Persistence.Entities.ComandaItem", b =>
                {
                    b.HasOne("Orion.Infrastructure.Persistence.Entities.Atendimento", "Atendimento")
                        .WithMany("Itens")
                        .HasForeignKey("AtendimentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atendimento");
                });

            modelBuilder.Entity("Orion.Infrastructure.Persistence.Entities.EntradaEstoqueItem", b =>
                {
                    b.HasOne("Orion.Infrastructure.Persistence.Entities.EntradaEstoque", "Entrada")
                        .WithMany("Itens")
                        .HasForeignKey("EntradaEstoqueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entrada");
                });

            modelBuilder.Entity("Orion.Infrastructure.Persistence.Entities.Mesa", b =>
                {
                    b.HasOne("Orion.Infrastructure.Persistence.Entities.Ambiente", "Ambiente")
                        .WithMany("Mesas")
                        .HasForeignKey("AmbienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ambiente");
                });

            modelBuilder.Entity("Orion.Infrastructure.Persistence.Entities.Ambiente", b =>
                {
                    b.Navigation("Mesas");
                });

            modelBuilder.Entity("Orion.Infrastructure.Persistence.Entities.Atendimento", b =>
                {
                    b.Navigation("Itens");

                    b.Navigation("Lugares");
                });

            modelBuilder.Entity("Orion.Infrastructure.Persistence.Entities.CartaCategoria", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("Orion.Infrastructure.Persistence.Entities.EntradaEstoque", b =>
                {
                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
