// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Orion.Infrastructure.Persistence;

#nullable disable

namespace Orion.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(OrionDbContext))]
    partial class OrionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("orion")
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Orion.Infrastructure.Persistence.Entities.EntradaEstoque", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CanceladoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelado_em");

                    b.Property<int?>("CanceladoPorUsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("cancelado_por_usuario_id");

                    b.Property<string>("ChaveAcesso")
                        .HasMaxLength(44)
                        .HasColumnType("character varying(44)")
                        .HasColumnName("chave_acesso");

                    b.Property<Guid>("ChaveIdempotencia")
                        .HasColumnType("uuid")
                        .HasColumnName("chave_idempotencia");

                    b.Property<DateTime?>("ConfirmadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmado_em");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<int>("CriadoPorUsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("criado_por_usuario_id");

                    b.Property<DateTime?>("DataEmissao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_emissao");

                    b.Property<DateTime>("DataEntrada")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_entrada");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("integer")
                        .HasColumnName("empresa_id");

                    b.Property<string>("FornecedorCnpj")
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("fornecedor_cnpj");

                    b.Property<long?>("FornecedorId")
                        .HasColumnType("bigint")
                        .HasColumnName("fornecedor_id");

                    b.Property<string>("FornecedorNome")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("fornecedor_nome");

                    b.Property<string>("ModeloFiscal")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("modelo_fiscal");

                    b.Property<string>("NumeroNf")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("numero_nf");

                    b.Property<string>("Observacao")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("observacao");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("origem");

                    b.Property<string>("OrigemCadastro")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("origem_cadastro");

                    b.Property<string>("ReferenciaExternaCore")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("referencia_externa_core");

                    b.Property<string>("Serie")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("serie");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo");

                    b.Property<int>("UnidadeId")
                        .HasColumnType("integer")
                        .HasColumnName("unidade_id");

                    b.Property<decimal?>("ValorTotal")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("valor_total");

                    b.Property<string>("XmlOriginal")
                        .HasColumnType("text")
                        .HasColumnName("xml_original");

                    b.HasKey("Id");

                    b.HasIndex("ChaveIdempotencia")
                        .IsUnique();

                    b.HasIndex("EmpresaId", "ChaveAcesso")
                        .IsUnique()
                        .HasFilter("chave_acesso IS NOT NULL");

                    b.HasIndex("EmpresaId", "Status", "DataEntrada");

                    b.ToTable("entradas_estoque", "orion");
                });

            modelBuilder.Entity("Orion.Infrastructure.Persistence.Entities.EntradaEstoqueItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CodigoBarrasNf")
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("codigo_barras_nf");

                    b.Property<string>("DescricaoNf")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("descricao_nf");

                    b.Property<long>("EntradaEstoqueId")
                        .HasColumnType("bigint")
                        .HasColumnName("entrada_estoque_id");

                    b.Property<decimal>("FatorConversao")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(15, 4)
                        .HasColumnType("numeric(15,4)")
                        .HasDefaultValue(1m)
                        .HasColumnName("fator_conversao");

                    b.Property<string>("MotivoDivergencia")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("motivo_divergencia");

                    b.Property<long?>("MovimentacaoCoreId")
                        .HasColumnType("bigint")
                        .HasColumnName("movimentacao_core_id");

                    b.Property<string>("Ncm")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("ncm");

                    b.Property<string>("ProdutoCodigo")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("produto_codigo");

                    b.Property<int?>("ProdutoCoreId")
                        .HasColumnType("integer")
                        .HasColumnName("produto_core_id");

                    b.Property<decimal?>("QuantidadeNf")
                        .HasPrecision(15, 3)
                        .HasColumnType("numeric(15,3)")
                        .HasColumnName("quantidade_nf");

                    b.Property<decimal>("QuantidadeRecebida")
                        .HasPrecision(15, 3)
                        .HasColumnType("numeric(15,3)")
                        .HasColumnName("quantidade_recebida");

                    b.Property<string>("ReferenciaExternaItem")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("referencia_externa_item");

                    b.Property<string>("StatusVinculo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status_vinculo");

                    b.Property<string>("UnidadeComercialNf")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("unidade_comercial_nf");

                    b.Property<decimal?>("ValorUnitarioNf")
                        .HasPrecision(15, 4)
                        .HasColumnType("numeric(15,4)")
                        .HasColumnName("valor_unitario_nf");

                    b.HasKey("Id");

                    b.HasIndex("EntradaEstoqueId");

                    b.ToTable("entradas_estoque_itens", "orion");
                });

            modelBuilder.Entity("Orion.Infrastructure.Persistence.Entities.Fornecedor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("Cnpj")
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("cnpj");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("integer")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "Cnpj")
                        .IsUnique()
                        .HasFilter("cnpj IS NOT NULL");

                    b.HasIndex("EmpresaId", "Nome");

                    b.ToTable("fornecedores", "orion");
                });

            modelBuilder.Entity("Orion.Infrastructure.Persistence.Entities.MapaCodigoBarras", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("CodigoBarras")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("codigo_barras");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("integer")
                        .HasColumnName("empresa_id");

                    b.Property<int>("ProdutoCoreId")
                        .HasColumnType("integer")
                        .HasColumnName("produto_core_id");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "CodigoBarras")
                        .IsUnique();

                    b.ToTable("mapa_codigo_barras", "orion");
                });

            modelBuilder.Entity("Orion.Infrastructure.Persistence.Entities.EntradaEstoqueItem", b =>
                {
                    b.HasOne("Orion.Infrastructure.Persistence.Entities.EntradaEstoque", "Entrada")
                        .WithMany("Itens")
                        .HasForeignKey("EntradaEstoqueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entrada");
                });

            modelBuilder.Entity("Orion.Infrastructure.Persistence.Entities.EntradaEstoque", b =>
                {
                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
