<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <RootNamespace>Orion.API</RootNamespace>
    <UserSecretsId>05af4a9a-d95f-42de-8e3c-63fd2ad6c4a1</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Orion.Application/Orion.Application.csproj" />
    <ProjectReference Include="../Orion.Infrastructure/Orion.Infrastructure.csproj" />
    <ProjectReference Include="../Orion.Core/Orion.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.8">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>
</Project>
